# Data Preparation III - Feature Selection: **Wrapper Method**

In [1]:
# Read the cleaned dataset (clean_df.csv) into a DataFrame and display the first few rows
import pandas as pd

df_clean = pd.read_csv('clean_df.csv')
display(df_clean.head())

,Unnamed: 0,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,...,num-of-cylinders_twelve,num-of-cylinders_two,fuel-system_1bbl,fuel-system_2bbl,fuel-system_4bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi
0,0,3,122.0,88.6,168.8,64.1,48.8,2548,130,3.47,...,0,0,0,0,0,0,0,1,0,0
1,1,3,122.0,88.6,168.8,64.1,48.8,2548,130,3.47,...,0,0,0,0,0,0,0,1,0,0
2,2,1,122.0,94.5,171.2,65.5,52.4,2823,152,2.68,...,0,0,0,0,0,0,0,1,0,0
3,3,2,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,...,0,0,0,0,0,0,0,1,0,0
4,4,2,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,...,0,0,0,0,0,0,0,1,0,0

#### Convert horsepower-binned from categorical to numeric using Ordinal Encoding

In [2]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[['Low', 'Medium', 'High']])
encoded_horse = encoder.fit_transform(df_clean[["horsepower-binned"]])

print(f"Encoded horsepower-binned: {encoded_horse}")

Encoded horsepower-binned: [[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]]

In [3]:
# merge the new dataframe to the original datafram
encoded_horse_df = pd.DataFrame(encoded_horse, columns=['horsepower-binned_encoded'])
df_clean = pd.concat([df_clean, encoded_horse_df], axis=1)

# drop original column "horsepower-binned" from "df"
df_clean = df_clean.drop('horsepower-binned', axis = 1)

In [4]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 77 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Unnamed: 0                 201 non-null    int64
 1   symboling                  201 non-null    int64
 2   normalized-losses          201 non-null    float64
 3   wheel-base                 201 non-null    float64
 4   length                     201 non-null    float64
 5   width                      201 non-null    float64
 6   height                     201 non-null    float64
 7   curb-weight                201 non-null    int64
 8   engine-size                201 non-null    int64
 9   bore                       201 non-null    float64
 10  stroke                     201 non-null    float64
 11  compression-ratio          201 non-null    float64
 12  horsepower                 201 non-null    float64
 13  peak-rpm                   201 non-null    float64
 14  city-mpg                   201 non-null    int64
 15  highway-mpg                201 non-null    int64
 16  price                      201 non-null    float64
 17  make_alfa-romero           201 non-null    int64
 18  make_audi                  201 non-null    int64
 19  make_bmw                   201 non-null    int64
 20  make_chevrolet             201 non-null    int64
 21  make_dodge                 201 non-null    int64
 22  make_honda                 201 non-null    int64
 23  make_isuzu                 201 non-null    int64
 24  make_jaguar                201 non-null    int64
 25  make_mazda                 201 non-null    int64
 26  make_mercedes-benz         201 non-null    int64
 27  make_mercury               201 non-null    int64
 28  make_mitsubishi            201 non-null    int64
 29  make_nissan                201 non-null    int64
 30  make_peugot                201 non-null    int64
 31  make_plymouth              201 non-null    int64
 32  make_porsche               201 non-null    int64
 33  make_renault               201 non-null    int64
 34  make_saab                  201 non-null    int64
 35  make_subaru                201 non-null    int64
 36  make_toyota                201 non-null    int64
 37  make_volkswagen            201 non-null    int64
 38  make_volvo                 201 non-null    int64
 39  fuel-type_diesel           201 non-null    int64
 40  fuel-type_gas              201 non-null    int64
 41  aspiration_std             201 non-null    int64
 42  aspiration_turbo           201 non-null    int64
 43  num-of-doors_four          201 non-null    int64
 44  num-of-doors_two           201 non-null    int64
 45  body-style_convertible     201 non-null    int64
 46  body-style_hardtop         201 non-null    int64
 47  body-style_hatchback       201 non-null    int64
 48  body-style_sedan           201 non-null    int64
 49  body-style_wagon           201 non-null    int64
 50  drive-wheels_4wd           201 non-null    int64
 51  drive-wheels_fwd           201 non-null    int64
 52  drive-wheels_rwd           201 non-null    int64
 53  engine-location_front      201 non-null    int64
 54  engine-location_rear       201 non-null    int64
 55  engine-type_dohc           201 non-null    int64
 56  engine-type_l              201 non-null    int64
 57  engine-type_ohc            201 non-null    int64
 58  engine-type_ohcf           201 non-null    int64
 59  engine-type_ohcv           201 non-null    int64
 60  engine-type_rotor          201 non-null    int64
 61  num-of-cylinders_eight     201 non-null    int64
 62  num-of-cylinders_five      201 non-null    int64
 63  num-of-cylinders_four      201 non-null    int64
 64  num-of-cylinders_six       201 non-null    int64
 65  num-of-cylinders_three     201 non-null    int64
 66  num-of-cylinders_twelve    201 non-null    int64
 67  num-of-cylinders_two       201 non-null    int64
 68  fuel-system_1bbl           201 non-null    int64
 69  fuel-system_2bbl           201 non-null    int64
 70  fuel-system_4bbl           201 non-null    int64
 71  fuel-system_idi            201 non-null    int64
 72  fuel-system_mfi            201 non-null    int64
 73  fuel-system_mpfi           201 non-null    int64
 74  fuel-system_spdi           201 non-null    int64
 75  fuel-system_spfi           201 non-null    int64
 76  horsepower-binned_encoded  201 non-null    float64
dtypes: float64(12), int64(65)
memory usage: 121.0 KB

In [5]:
# drop the first column "unnamed" since it is just an ID (not used)
df_clean = df_clean.drop('Unnamed: 0', axis = 1)

In [6]:
# Move the target variable "price" to the last column
# Get a list of all columns
cols = df_clean.columns.tolist()

# Remove 'price' from the list
cols.remove('price')

# Append 'price' to the end of the list
cols.append('price')

# Reindex the DataFrame with the new column order
df_clean = df_clean[cols]

# Display the columns to confirm the change
print(df_clean.columns)

Index(['symboling', 'normalized-losses', 'wheel-base', 'length', 'width',
       'height', 'curb-weight', 'engine-size', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'make_alfa-romero', 'make_audi', 'make_bmw',
       'make_chevrolet', 'make_dodge', 'make_honda', 'make_isuzu',
       'make_jaguar', 'make_mazda', 'make_mercedes-benz', 'make_mercury',
       'make_mitsubishi', 'make_nissan', 'make_peugot', 'make_plymouth',
       'make_porsche', 'make_renault', 'make_saab', 'make_subaru',
       'make_toyota', 'make_volkswagen', 'make_volvo', 'fuel-type_diesel',
       'fuel-type_gas', 'aspiration_std', 'aspiration_turbo',
       'num-of-doors_four', 'num-of-doors_two', 'body-style_convertible',
       'body-style_hardtop', 'body-style_hatchback', 'body-style_sedan',
       'body-style_wagon', 'drive-wheels_4wd', 'drive-wheels_fwd',
       'drive-wheels_rwd', 'engine-location_front', 'engine-location_rear',
       'engine-type_dohc', 'engine-type_l', 'engine-type_ohc',
       'engine-type_ohcf', 'engine-type_ohcv', 'engine-type_rotor',
       'num-of-cylinders_eight', 'num-of-cylinders_five',
       'num-of-cylinders_four', 'num-of-cylinders_six',
       'num-of-cylinders_three', 'num-of-cylinders_twelve',
       'num-of-cylinders_two', 'fuel-system_1bbl', 'fuel-system_2bbl',
       'fuel-system_4bbl', 'fuel-system_idi', 'fuel-system_mfi',
       'fuel-system_mpfi', 'fuel-system_spdi', 'fuel-system_spfi',
       'horsepower-binned_encoded', 'price'],
      dtype='object')

# Feature Selection Methods
The following are methods for feature selection:

1. Filter: filters features based on the statistical indicators for the feature vectors and those common to the feature vectors and the target variables.
2. Wrapper: attempts to use different feature subsets for modeling and use the model precision as an evaluation indicator for the feature subsets.
3. Embedded: evaluates feature weights during model training and scores the importance of the features.

##2. Wrapper

## Wrapper
In the wrapper selection method, different feature subsets are used for modeling, the model precision
is used as the evaluation indicator for the feature subsets, and a base model is selected to perform multi-round training. After each round of training, features of some weight coefficients are removed, and then the next round of training is performed based on the new feature set. The RFE() method of the feature_selection submodule in sklearn is invoked. The logistic regression model LogisticRegressio() is used as the base model to be invoked, and parameter will be transferred into
this model.

Wrapper:

estimator: basic training model, which is a logistic regression model in this example.

n_features_to_select: indicates the number of retained features.


fit(X,y): invokes and trains a model.

In [7]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import Ridge

# Split the column into X (independent variables/input) and y (target/output)
X = df_clean.drop('price',axis=1)
y = df_clean['price']

x_rfe=RFE(estimator=Ridge(alpha=.5), n_features_to_select=20).fit(X, y)
print(x_rfe.n_features_ )
print(x_rfe.support_ )
print(x_rfe.ranking_ )
print(x_rfe.estimator_ )

20
[False False False False  True False False False  True False False False
 False False False False False  True False False False False  True False
  True  True False False  True False  True  True  True  True False False
 False False False False False False False  True False False False False
 False  True False  True  True False False False False  True  True  True
 False  True False False False False False False False False False False
 False False  True]
[39 54 35 47  1 36 55 43  1 33 25 51 56 41 42 46 16  1 12 11 32 14  1  7
  1  1  6  8  1  9  1  1  1  1  5 10 44 20 24 29 34 48 49  1 37 17 19 18
 26  1 27  1  1 52 21 30 28  1  1  1  4  1 22 31  3  2 13 50 45 23 15 53
 40 38  1]
Ridge(alpha=0.5)

##Variable Removal
Based on the results of the preceding selection method, the variables that have a small model impact weight are removed.

In [8]:
# Based on the results of the preceding selection method, the variables that have a small model impact weight are removed.
del_cols = X.columns[~x_rfe.support_].tolist()
df_select = df_clean.drop(del_cols,axis=1)
df_select.head()

,width,bore,make_bmw,make_jaguar,make_mercedes-benz,make_mercury,make_peugot,make_porsche,make_renault,make_saab,...,body-style_convertible,drive-wheels_fwd,engine-location_front,engine-location_rear,engine-type_ohcv,engine-type_rotor,num-of-cylinders_eight,num-of-cylinders_four,horsepower-binned_encoded,price
0,64.1,3.47,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,1,0.0,13495.0
1,64.1,3.47,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,1,0.0,16500.0
2,65.5,2.68,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,1.0,16500.0
3,66.2,3.19,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,0.0,13950.0
4,66.4,3.19,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0.0,17450.0